name: fth

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  fth:
    type: tool
    platform: macOS
    sources:
      - path: src/
      - path: fth.c
      - path: fth.h
        type: folder
      - path: README.md
        type: folder
      - path: project.yml
        type: folder
      - path: test.f
        type: folder
